"""add_job_progress

Revision ID: 014daa922afc
Revises: 0a24070c327f
Create Date: 2026-01-10 17:26:22.210419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '014daa922afc'
down_revision: Union[str, Sequence[str], None] = '0a24070c327f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'jobs',
        sa.Column(
            'current_step',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    op.add_column(
        'jobs',
        sa.Column('steps_completed', sa.Integer(), nullable=False, server_default=sa.text('0')),
    )
    op.add_column(
        'jobs',
        sa.Column('steps_total', sa.Integer(), nullable=False, server_default=sa.text('0')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'steps_total')
    op.drop_column('jobs', 'steps_completed')
    op.drop_column('jobs', 'current_step')
    # ### end Alembic commands ###
