"""add_content_text

Revision ID: 06180cac387c
Revises: 581d4d1634a4
Create Date: 2026-01-10 22:00:29.888943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '06180cac387c'
down_revision: Union[str, Sequence[str], None] = '581d4d1634a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_docs', sa.Column('content_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_docs', 'content_text')
    # ### end Alembic commands ###
