"""chore: sync migrations

Revision ID: 4f8f52de7276
Revises: m7j4e5f6g7h
Create Date: 2026-02-15 19:30:02.408093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlmodel.sql.sqltypes import AutoString

sourcetype_enum = postgresql.ENUM("WEB", "REDDIT", "YOUTUBE", name="sourcetype")


# revision identifiers, used by Alembic.
revision: str = '4f8f52de7276'
down_revision: Union[str, Sequence[str], None] = 'm7j4e5f6g7h'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('research_nodes', 'source_url',
               existing_type=sa.TEXT(),
               type_=AutoString(),
               existing_nullable=True)
    op.alter_column('research_nodes', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('research_nodes', 'is_suppressed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # 1) ensure enum exists
    sourcetype_enum.create(op.get_bind(), checkfirst=True)
    # 2) drop old default (this is what is failing)
    op.execute("ALTER TABLE source_docs ALTER COLUMN source_type DROP DEFAULT")
    # 3) change type with USING cast
    op.execute(
        "ALTER TABLE source_docs "
        "ALTER COLUMN source_type TYPE sourcetype "
        "USING source_type::sourcetype"
    )
    # 4) optional: set default back (ONLY if you need a default)
    op.execute("ALTER TABLE source_docs ALTER COLUMN source_type SET DEFAULT 'WEB'::sourcetype")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE source_docs ALTER COLUMN source_type DROP DEFAULT")
    op.execute(
        "ALTER TABLE source_docs "
        "ALTER COLUMN source_type TYPE TEXT "
        "USING source_type::text"
    )
    sourcetype_enum.drop(op.get_bind(), checkfirst=True)
    op.alter_column('research_nodes', 'is_suppressed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('research_nodes', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('research_nodes', 'source_url',
               existing_type=AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
