"""chore: sync migrations

Revision ID: 4f8f52de7276
Revises: m7j4e5f6g7h
Create Date: 2026-02-15 19:30:02.408093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f8f52de7276'
down_revision: Union[str, Sequence[str], None] = 'm7j4e5f6g7h'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('research_nodes', 'source_url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('research_nodes', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('research_nodes', 'is_suppressed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('source_docs', 'source_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('WEB', 'REDDIT', 'YOUTUBE', name='sourcetype'),
               existing_nullable=False,
               existing_server_default=sa.text("'WEB'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_docs', 'source_type',
               existing_type=sa.Enum('WEB', 'REDDIT', 'YOUTUBE', name='sourcetype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'WEB'::character varying"))
    op.alter_column('research_nodes', 'is_suppressed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('research_nodes', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('research_nodes', 'source_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
