"""ensure_projects_table

Revision ID: b93e7e3ec5fc
Revises: a1b56672dc1d
Create Date: 2026-01-16 20:48:09.653863

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'b93e7e3ec5fc'
down_revision: Union[str, Sequence[str], None] = 'a1b56672dc1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
