"""add_source_title

Revision ID: c69cefd60a8a
Revises: 4846ef2e6ec1
Create Date: 2026-01-11 09:24:58.267434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c69cefd60a8a'
down_revision: Union[str, Sequence[str], None] = '4846ef2e6ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
