"""add_source_title

Revision ID: e569e5542f36
Revises: 06180cac387c
Create Date: 2026-01-11 08:14:05.957425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e569e5542f36'
down_revision: Union[str, Sequence[str], None] = '06180cac387c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_docs', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_docs', 'title')
    # ### end Alembic commands ###
